apiVersion: v1
kind: Service
metadata:
  name: arcadebackend
  labels:
    name: arcadebackend    
spec:
  selector:
    name: arcadebackend    
  type: LoadBalancer
  ports:
   - port: 80
     name: arcadebackend
     targetPort: 8080
     protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadebackend
spec:
  # replicas: 3
  selector:
    matchLabels:
      name: arcadebackend      
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: arcadebackend        
    spec:
      # imagePullSecrets:
      #   - name: teamregistry
      containers:
      - name: arcadebackend
        image: ghcr.io/azure-adventure-day/azure-adventure-day-coach/gamebot:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: arcadebackend         
            protocol: TCP
        env: 
          - name: "PORT"
            value: "8080"
          - name: "PICK_STRATEGY"
            value: "RANDOM"
          - name: "FF_BETS"
            value: "1"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            cpu: 0.25
          limits:
            cpu: 0.5
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2020-11-12T12:47:40Z","reason":"ScaleDownStabilized","message":"recent
      recommendations were higher than current one, applying the highest recent recommendation"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2020-11-12T12:59:05Z","reason":"ValidMetricFound","message":"the
      HPA was able to successfully calculate a replica count from cpu resource utilization
      (percentage of request)"},{"type":"ScalingLimited","status":"False","lastTransitionTime":"2020-11-12T12:59:05Z","reason":"DesiredWithinRange","message":"the
      desired count is within the acceptable range"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":13,"currentAverageValue":"34m"}}]'
  name: arcadebackend
  namespace: default
  resourceVersion: "30218"
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: arcadebackend
  targetCPUUtilizationPercentage: 20
